baseURL = "https://hashtag-fr.github.io/lxya.github.io/"
languageCode = "en-us"
title = "Lxya Blog"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
author = "Lxya"
description = "AI and Technology Blog"

relativeURLs = true
canonifyURLs = true